version: "3.4"
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  web:
      restart: always
      environment:
        - DJANGO_SECRET_KEY=local
        - PORT=8000
      build: ./
      command: >
        bash -c "python wait_for_postgres.py &&
                ./manage.py migrate &&
                honcho start"
      volumes:
        - .:/code/app
      ports:
        - "8000:8000"
      depends_on:
        - db
volumes:
  postgres_data: